metadata:
- appName: ''
  dataId: autumn-auth.yml
  group: dev
  type: yaml
- appName: ''
  dataId: autumn-gateway.yml
  group: dev
  type: yaml
- appName: ''
  dataId: common-mybatis.yml
  group: dev
  type: yaml
- appName: ''
  dataId: common-oss.yml
  group: dev
  type: yaml
- appName: ''
  dataId: common-rabbitmq.yml
  group: dev
  type: yaml
- appName: ''
  dataId: common-redis.yml
  group: dev
  type: yaml
- appName: ''
  dataId: content-service.yml
  group: dev
  type: yaml
- appName: ''
  dataId: media-service.yml
  group: dev
  type: yaml
