mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1   # 已删除的值
      logic-not-delete-value: 0  # 未删除的值
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志